// Chunk 0 of the free-limit Mobius domain-wall preconditioner (Grid port).
// See dwf4_qcd_claude/grid_dwf_prec_impl_plan_claude.md.
//
// Gate 0 = free-operator convention gate, config-INDEPENDENT, validates the momentum-space SPECTRAL
// BLOCK ("the eigenvalues") that replaces Grid's Shamir-only FreePropagator momentum kernel:
//   0a: free D_W(p) eigenvalues = d +- i sqrt(S)   [d = (Nd-M5) - sum cos p, S = sum sin^2 p]
//   0b: free Mobius block (4 Ls)x(4 Ls) min/max |lambda| vs grid_validation_evals_claude.md
// Reference table generated by dwf4_free_evals_claude.py; must match to ~1e-4 (table printed to 7 sig
// figs; the underlying construction agrees to ~1e-12).
//
// NB (user 2026-08-31): Shamir -> Mobius changes eigenvalues AND eigenvectors, so gate 0b is
// NECESSARY-BUT-NOT-SUFFICIENT; the full inverse (values + vectors) is checked by the chunk-1 cold gate.

#include <Grid/Grid.h>
#include <Grid/qcd/utils/FreeMobius5D_claude.h>

#include <array>
#include <vector>
#include <complex>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <string>

using namespace Grid;

// sort complex numbers by (real, then imag) -- for the similarity-invariant eigenvalue SET compare
static bool cmp_cplx(const std::complex<double>& a, const std::complex<double>& b) {
  if (a.real() != b.real()) {
    return a.real() < b.real();
  }
  return a.imag() < b.imag();
}

// Flow-frame + FGMRES(M0)-vs-CGNE D_W-apply benchmark on config U (solve the ORIGINAL U).
// Frame = WilsonFlow(flow_eps x flow_nstep) then Fourier Landau (Omega_tol 1e-12). Metric (dwf4):
// D_W applies = CGNE 2*Ls*iters (normal op = 2 M/iter), FGMRES Ls*iters (1 M/iter; M0 costs 0 D_W).
// Right-preconditioned non-Hermitian operator P = D o M0 (apply M0 then D) for short-recurrence solvers
// (BiCGSTAB) that take a bare LinearOperatorBase (no built-in preconditioner). Solve P y = b -> x = M0 y
// solves D x = b. BiCGSTAB uses Op() only; the rest assert (not called).
template <class Field>
class RightPrecOp : public LinearOperatorBase<Field> {
public:
  LinearOperatorBase<Field>& Dop;
  LinearFunction<Field>& Prec;
  Field tmp;
  RightPrecOp(LinearOperatorBase<Field>& D_, LinearFunction<Field>& M_, GridBase* g)
    : Dop(D_), Prec(M_), tmp(g) {}
  void Op(const Field& in, Field& out) {
    Prec(in, tmp);
    Dop.Op(tmp, out);
  }
  void AdjOp(const Field& in, Field& out) { assert(0); }
  void OpDiag(const Field& in, Field& out) { assert(0); }
  void OpDir(const Field& in, Field& out, int dir, int disp) { assert(0); }
  void OpDirAll(const Field& in, std::vector<Field>& out) { assert(0); }
  void HermOp(const Field& in, Field& out) { assert(0); }
  void HermOpAndNorm(const Field& in, Field& out, RealD& n1, RealD& n2) { assert(0); }
};

// outer-solver knobs (main sets from CLI): FGMRES restart length; whether to run the BiCGSTAB A/B.
// default 256 = NO-RESTART. Restarting is CATASTROPHIC for F-preconditioned FGMRES: the win is
// "deflation-by-recurrence" (the growing Krylov subspace IS the deflation), so a restart destroys it.
// Peter Boyle's window scan (harder regime): no-restart 233 iters -> window-128 829 -> window-32 3353 ->
// window-16 unconverged. My 8^4 m=0.1 sweep (restart 32 = only +15% iters) was too EASY to see this; do
// NOT restart. (Memory is the real cost of no-restart; the MG smoother-slot build is what removes it.)
static int g_fgmres_restart = 256;
static bool g_run_bcg = false;
static std::vector<int> g_restart_sweep;  // if set (--restart-sweep a,b,c), FGMRES solves each back-to-back

static void run_headline(const std::string& tag, LatticeGaugeFieldD& U,
                         GridCartesian* UGrid, GridRedBlackCartesian* UrbGrid,
                         GridCartesian* FGrid, GridRedBlackCartesian* FrbGrid,
                         int Ls, double M5, double bb, double cc, double mm,
                         std::vector<Complex> boundary, double flow_eps, int flow_nstep,
                         GridParallelRNG& RNG5, bool run_cgne, bool run_m0, bool run_m1) {
  std::cout << "==== headline: FGMRES(M0) vs CGNE D_W-count  [" << tag << "] ====" << std::endl;

  Real plaq0 = WilsonLoops<PeriodicGimplD>::avgPlaquette(U);
  LatticeGaugeFieldD Uflowed(UGrid);
  WilsonFlow<PeriodicGimplD> wf(flow_eps, flow_nstep);
  wf.smear(Uflowed, U);
  Real plaq_flowed = WilsonLoops<PeriodicGimplD>::avgPlaquette(Uflowed);
  LatticeColourMatrixD xform(UGrid);
  // Landau fix. Grid's FourierAccelSteepestDescentStep weights the force by psqMax/psq with psqMax=16
  // (GaugeFix.h:198-199), i.e. a step 16x LARGER than the dwf4 reference weight 1/psq. At alpha=0.1 that
  // OVERSHOOTS and diverges (dmuAmu 254 @it20 -> ~28000 stuck). Use alpha = 0.1/16 to reproduce dwf4's
  // stable step; it then decreases monotonically to the flowed-fixed plateau. FA Landau gauge fixing:
  // C.T.H. Davies et al., PRD 37 (1988) 1581.
  RealD gf_alpha = 0.1 / 16.0;
  // Frame convergence scales with volume: the softest mode phat^2_min = 2-2cos(2pi/L) shrinks with L
  // (~0.586 at L=8 vs 2.0 at L=4), so the FA fixer needs MORE iters at larger volume. 1000 is generous
  // insurance (the alpha=0.00625 step is stable/monotone, so extra iters only converge further); watch
  // the printed dmuAmu/functional plateau to confirm convergence.
  int gf_maxit = 1000;
  FourierAcceleratedGaugeFixer<PeriodicGimplD>::SteepestDescentGaugeFix(
      Uflowed, xform, gf_alpha, gf_maxit, 1.0e-12, 1.0e-12, /*Fourier=*/true, /*orthog=*/-1,
      /*err_on_no_converge=*/false);
  Real landau = 1.0 - WilsonLoops<PeriodicGimplD>::linkTrace(Uflowed);
  Real Q = WilsonLoops<PeriodicGimplD>::TopologicalCharge(U);
  // Q_5Li on the SAME Uflowed used to build Omega = the frame-flow charge. If it sits on the integer,
  // the tau=2 Wilson flow did NOT destroy the instanton (the lump survives into the frame). 5Li is the
  // clean measure here; Q(orig) above is UV-noisy clover on the rough config -- not the physics Q.
  Real Qflow = WilsonLoops<PeriodicGimplD>::TopologicalCharge5Li(Uflowed);
  std::cout << "  plaq=" << plaq0 << "  flowed plaq=" << plaq_flowed
            << "  flowed-fixed Landau functional=" << landau << "  Q(orig)=" << Q
            << "  Q_5Li(frame-flowed tau=" << (flow_eps * flow_nstep) << ")=" << Qflow << std::endl;

  WilsonImplD::ImplParams Params(boundary);
  MobiusFermionD D(U, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
  FreeMobius5DInverse<WilsonImplD> Ffree(FGrid, Ls, M5, bb, cc, mm, boundary);
  FreeLimitPreconditioner<WilsonImplD> M0(Ffree, xform, FGrid);

  LatticeFermionD bsrc(FGrid);
  gaussian(RNG5, bsrc);
  RealD solve_tol = 1.0e-8;
  int solve_maxit = 4000;
  int fgmres_restart = 256;  // no-restart: RestartLength >> expected iters, not literally maxit (OOM)

  // LinOp on the ORIGINAL operator D, shared by the M0 and M1 FGMRES solves.
  NonHermitianLinearOperator<MobiusFermionD, LatticeFermionD> LinOp(D);

  // ADDITIVE op selection (Nobu): run_cgne / run_m0 / run_m1 each turn ON a solve; nothing is
  // force-skipped. Each op's D_W count is printed on its own; cross-op ratios that need a count NOT
  // computed this run (e.g. FGMRES-M1 speedup vs CGNE when only --ops m1) are taken from the prior
  // freeprec_<cfg>_claude.log. flow + Landau above always run (M0 and M1 both need Omega / U^L).
  long dW_cgne = 0;
  if (run_cgne) {
    // CGNE baseline: CG on MdagM, src = Mdag b
    MdagMLinearOperator<MobiusFermionD, LatticeFermionD> HermOp(D);
    LatticeFermionD bn(FGrid);
    D.Mdag(bsrc, bn);
    LatticeFermionD xcg(FGrid);
    xcg = Zero();
    ConjugateGradient<LatticeFermionD> CG(solve_tol, solve_maxit);
    CG(HermOp, bn, xcg);
    int cg_iters = CG.IterationsToComplete;
    dW_cgne = (long)2 * Ls * cg_iters;
    std::cout << "  CGNE:       iters=" << cg_iters << "  D_W applies=" << dW_cgne << std::endl;
  }

  if (run_m0) {
    // FGMRES right-preconditioned by M0. If --restart-sweep given, solve at each restart length
    // BACK-TO-BACK (same frame + GPU load -> removes cross-run drift, pins the restart optimum); else a
    // single solve at g_fgmres_restart (default = no-restart).
    std::vector<int> restarts = g_restart_sweep.empty() ? std::vector<int>({g_fgmres_restart})
                                                        : g_restart_sweep;
    for (size_t ri = 0; ri < restarts.size(); ++ri) {
      int rl = restarts[ri];
      M0.reset_timers();  // zeroes n_apply + all M0/F usecond accumulators
      FlexibleGeneralisedMinimalResidual<LatticeFermionD> FGMRES(solve_tol, solve_maxit, M0,
                                                                rl, /*err_on_no_conv=*/false);
      LatticeFermionD xg(FGrid);
      xg = Zero();
      double tw_fg = -usecond();
      FGMRES(LinOp, bsrc, xg);
      tw_fg += usecond();
      int fg_iters = FGMRES.IterationCount;
      long dW_fgmres = (long)Ls * fg_iters;
      std::cout << "  FGMRES(M0) restart=" << rl << ": iters=" << fg_iters
                << "  M0 applies=" << M0.n_apply << "  D_W applies=" << dW_fgmres
                << "  WALL=" << tw_fg / 1.0e6 << " s" << std::endl;
      if (dW_cgne > 0) {
        double speedup = (dW_fgmres > 0) ? (double)dW_cgne / (double)dW_fgmres : 0.0;
        std::cout << "  D_W-apply speedup (CGNE / FGMRES-M0) = " << speedup << "x" << std::endl;
      }
    }
    // COMPLETE-PICTURE benchmark: the full M0 apply breakdown (omega / phase / fft_fwd / solve /
    // fft_bwd), then a Dhop currency measured in the SAME run/layout so M0-vs-D_W is directly
    // comparable. The D_W-count speedup above is a COUNT; this converts M0 cost into Dhop units.
    M0.report_timers();
    LatticeFermionD dwin(FGrid);
    LatticeFermionD dwout(FGrid);
    gaussian(RNG5, dwin);
    D.Dhop(dwin, dwout, 0);  // warm up
    int ndw = 50;
    double tdw = -usecond();
    for (int i = 0; i < ndw; ++i) {
      D.Dhop(dwin, dwout, 0);
    }
    tdw += usecond();
    double dhop_us = tdw / (double)ndw;
    std::cout << GridLogMessage << "  [Dhop] us/apply = " << dhop_us << std::endl;
    if (M0.n_apply > 0) {
      double m0_us = (M0.t_omega + M0.t_free) / (double)M0.n_apply;
      std::cout << GridLogMessage << "  [M0/Dhop] full M0 apply = " << (m0_us / dhop_us)
                << " Dhop-equivalents  (M0 us/apply = " << m0_us << ")" << std::endl;
    }
  }

  if (g_run_bcg) {
    // BiCGSTAB right-preconditioned by M0 (short recurrence, NO orthogonalization; ~2 M0 applies/iter).
    // Solve (D M0) y = b, then x = M0 y. Compare WALL to FGMRES: BiCGSTAB drops the O(iters^2)
    // orthogonalization but pays 2 M0 applies/iter, so it wins only if it converges in fewer iters.
    M0.reset_timers();
    RightPrecOp<LatticeFermionD> P(LinOp, M0, FGrid);
    BiCGSTAB<LatticeFermionD> BCG(solve_tol, solve_maxit, /*err_on_no_conv=*/false);
    LatticeFermionD yb(FGrid);
    yb = Zero();
    double tw_bcg = -usecond();
    BCG(P, bsrc, yb);
    tw_bcg += usecond();
    LatticeFermionD xb(FGrid);
    M0(yb, xb);  // x = M0 y solves D x = b
    LatticeFermionD Dxb(FGrid);
    D.M(xb, Dxb);
    double res = std::sqrt(norm2(Dxb - bsrc) / norm2(bsrc));
    int bcg_iters = BCG.IterationsToComplete;
    long dW_bcg = (long)Ls * 2 * bcg_iters;  // 2 D-applies/iter via P.Op
    std::cout << "  BiCGSTAB(M0): iters=" << bcg_iters << "  M0 applies=" << M0.n_apply
              << "  D_W applies=" << dW_bcg << "  WALL=" << tw_bcg / 1.0e6 << " s  true res=" << res
              << std::endl;
  }

  if (run_m1) {
    // FGMRES right-preconditioned by M1 (leading D_W correction, EXACT split tildeA = U^L - 1).
    // U^L = Omega U Omega^dag (the ORIGINAL config framed); D_DW[U^L] is a second Mobius operator.
    LatticeGaugeFieldD UL(UGrid);
    UL = U;
    SU<Nc>::GaugeTransform<PeriodicGimplD>(UL, xform);  // U^L = Omega U Omega^dag, in place
    MobiusFermionD Dframed(UL, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
    FreeLimitPreconditioner1<WilsonImplD> M1(Ffree, xform, Dframed, FGrid);
    FlexibleGeneralisedMinimalResidual<LatticeFermionD> FGMRES1(solve_tol, solve_maxit, M1,
                                                               fgmres_restart, /*err_on_no_conv=*/false);
    LatticeFermionD xg1(FGrid);
    xg1 = Zero();
    FGMRES1(LinOp, bsrc, xg1);
    int fg1_iters = FGMRES1.IterationCount;
    // Honest metric: M1 is NOT D_W-free. Total = outer (Ls per FGMRES iter) + M1-internal D_DW[U^L]
    // (Ls per M1 apply). n_dw counts the framed-Mobius applies directly.
    long dW_fgmres1 = (long)Ls * fg1_iters + (long)Ls * M1.n_dw;
    std::cout << "  FGMRES(M1): iters=" << fg1_iters << "  M1 applies=" << M1.n_apply
              << "  internal D_DW[U^L]=" << M1.n_dw
              << "  D_W applies(total)=" << dW_fgmres1 << std::endl;
    if (dW_cgne > 0) {
      double speedup1 = (dW_fgmres1 > 0) ? (double)dW_cgne / (double)dW_fgmres1 : 0.0;
      std::cout << "  D_W-apply speedup (CGNE / FGMRES-M1) = " << speedup1 << "x" << std::endl;
    } else {
      std::cout << "  D_W-apply speedup (CGNE / FGMRES-M1) = n/a this run (divide the logged CGNE D_W by "
                << dW_fgmres1 << ")" << std::endl;
    }
  }
}

// Flow-time SCAN (Direction 1b Stage 1, freeprec_future_directions_claude.md): fix flow = Wilson, scan
// the frame-flow time. CGNE is FRAME-INDEPENDENT -> computed ONCE and reused for every tau. For each
// nstep (tau = flow_eps*nstep) we Wilson-flow, Landau-fix the frame Omega, and record the M0 (and M1)
// D_W-apply ratio vs s/t0 = tau/t0 (t0 measured per ensemble, memory project-r2-config-gen). One block
// per tau, flushed as it finishes so a walltime kill still leaves the completed tau points in the log.
static void run_flowscan(const std::string& tag, LatticeGaugeFieldD& U,
                         GridCartesian* UGrid, GridRedBlackCartesian* UrbGrid,
                         GridCartesian* FGrid, GridRedBlackCartesian* FrbGrid,
                         int Ls, double M5, double bb, double cc, double mm,
                         std::vector<Complex> boundary, double flow_eps,
                         const std::vector<int>& nsteps, double t0,
                         GridParallelRNG& RNG5, bool run_cgne, bool run_m0, bool run_m1,
                         double solve_tol) {
  std::cout << "==== flow-time scan (Wilson flow)  [" << tag << "]  t0=" << t0
            << "  tol=" << solve_tol << " ====" << std::endl;

  WilsonImplD::ImplParams Params(boundary);
  MobiusFermionD D(U, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
  FreeMobius5DInverse<WilsonImplD> Ffree(FGrid, Ls, M5, bb, cc, mm, boundary);

  LatticeFermionD bsrc(FGrid);
  gaussian(RNG5, bsrc);
  int solve_maxit = 4000;
  int fgmres_restart = 256;  // no-restart: RestartLength >> expected iters (not literally maxit; OOM)
  NonHermitianLinearOperator<MobiusFermionD, LatticeFermionD> LinOp(D);

  Real plaq0 = WilsonLoops<PeriodicGimplD>::avgPlaquette(U);
  std::cout << "  plaq=" << plaq0 << std::endl;

  // CGNE baseline depends only on D (the ORIGINAL operator), NOT the frame -> compute once, reuse.
  long dW_cgne = 0;
  if (run_cgne) {
    MdagMLinearOperator<MobiusFermionD, LatticeFermionD> HermOp(D);
    LatticeFermionD bn(FGrid);
    D.Mdag(bsrc, bn);
    LatticeFermionD xcg(FGrid);
    xcg = Zero();
    ConjugateGradient<LatticeFermionD> CG(solve_tol, solve_maxit);
    CG(HermOp, bn, xcg);
    int cg_iters = CG.IterationsToComplete;
    dW_cgne = (long)2 * Ls * cg_iters;
    std::cout << "  CGNE (frame-independent): iters=" << cg_iters << "  D_W applies=" << dW_cgne
              << std::endl;
  }

  RealD gf_alpha = 0.1 / 16.0;  // Grid FA step is 16x too large (see run_headline); use 0.1/16
  int gf_maxit = 1000;
  for (size_t i = 0; i < nsteps.size(); ++i) {
    int nstep = nsteps[i];
    RealD tau = flow_eps * nstep;
    RealD s_over_t0 = (t0 > 0.0) ? (tau / t0) : 0.0;

    LatticeGaugeFieldD Uflowed(UGrid);
    WilsonFlow<PeriodicGimplD> wf(flow_eps, nstep);
    wf.smear(Uflowed, U);
    LatticeColourMatrixD xform(UGrid);
    FourierAcceleratedGaugeFixer<PeriodicGimplD>::SteepestDescentGaugeFix(
        Uflowed, xform, gf_alpha, gf_maxit, 1.0e-12, 1.0e-12, /*Fourier=*/true, /*orthog=*/-1,
        /*err_on_no_converge=*/false);
    Real landau = 1.0 - WilsonLoops<PeriodicGimplD>::linkTrace(Uflowed);
    Real Qflow = WilsonLoops<PeriodicGimplD>::TopologicalCharge5Li(Uflowed);

    std::cout << "  ---- s/t0=" << s_over_t0 << "  tau=" << tau << "  nstep=" << nstep
              << "  Landau=" << landau << "  Q_5Li(flowed)=" << Qflow << " ----" << std::endl;

    FreeLimitPreconditioner<WilsonImplD> M0(Ffree, xform, FGrid);
    if (run_m0) {
      M0.n_apply = 0;
      FlexibleGeneralisedMinimalResidual<LatticeFermionD> FGMRES(solve_tol, solve_maxit, M0,
                                                                fgmres_restart, /*err_on_no_conv=*/false);
      LatticeFermionD xg(FGrid);
      xg = Zero();
      FGMRES(LinOp, bsrc, xg);
      int fg_iters = FGMRES.IterationCount;
      long dW_fgmres = (long)Ls * fg_iters;
      double ratio = (dW_cgne > 0 && dW_fgmres > 0) ? (double)dW_cgne / (double)dW_fgmres : 0.0;
      std::cout << "    M0: iters=" << fg_iters << "  D_W=" << dW_fgmres << "  ratio(CGNE/M0)=" << ratio
                << "x" << std::endl;
    }
    if (run_m1) {
      LatticeGaugeFieldD UL(UGrid);
      UL = U;
      SU<Nc>::GaugeTransform<PeriodicGimplD>(UL, xform);  // U^L = Omega U Omega^dag
      MobiusFermionD Dframed(UL, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
      FreeLimitPreconditioner1<WilsonImplD> M1(Ffree, xform, Dframed, FGrid);
      FlexibleGeneralisedMinimalResidual<LatticeFermionD> FGMRES1(solve_tol, solve_maxit, M1,
                                                                 fgmres_restart, /*err_on_no_conv=*/false);
      LatticeFermionD xg1(FGrid);
      xg1 = Zero();
      FGMRES1(LinOp, bsrc, xg1);
      int fg1_iters = FGMRES1.IterationCount;
      long dW_fgmres1 = (long)Ls * fg1_iters + (long)Ls * M1.n_dw;  // honest total (M1 not D_W-free)
      double ratio1 = (dW_cgne > 0 && dW_fgmres1 > 0) ? (double)dW_cgne / (double)dW_fgmres1 : 0.0;
      std::cout << "    M1: iters=" << fg1_iters << "  internal D_DW[U^L]=" << M1.n_dw
                << "  D_W(total)=" << dW_fgmres1 << "  ratio(CGNE/M1)=" << ratio1 << "x" << std::endl;
    }
    std::cout.flush();
  }
}

// 4^4 bit-exact gate: build D_W(-M5) (mass-normalized, AP-time) on the loaded config, form the dense
// (V4*Ns*Nc)x(...) matrix, compare its eigenvalue SET (sorted) to the dwf4 reference .dat. D_W
// eigenvalues are similarity-invariant, so the gamma basis need not match -- compare sorted sets.
static bool nersc_crosscheck(LatticeGaugeFieldD& Umu, const std::string& evalfile,
                             GridCartesian* UGrid, GridRedBlackCartesian* UrbGrid,
                             double M5, std::vector<Complex> boundary, bool full_spectrum) {
  std::cout << "==== chunk 3b: raw D_W(-M5) eigenvalue cross-check vs dwf4 ====" << std::endl;

  int V4 = (int)UGrid->gSites();
  int N = V4 * Ns * Nc;

  // The dense D_W eigenvalue cross-check is only feasible at 4^4 (N=3072). At 8^4 N=49152 -> a dense
  // matrix is ~38 GB and ZGEEV is O(N^3) hours, so the exporter ships NO eval .dat there. Skip the
  // dense build above 4^4; the config load-check (plaquette/checksum) + the D_W-apply count gate stand.
  if (V4 > 256) {
    std::cout << "  dense D_W cross-check SKIPPED (N=" << N << " infeasible above 4^4); relying on the "
              << "load-check (plaquette/checksum) + the CGNE-vs-FGMRES D_W-count gate." << std::endl;
    return true;
  }

  WilsonImplD::ImplParams Params(boundary);            // AP-time BC
  WilsonFermionD Dw(Umu, *UGrid, *UrbGrid, -M5, Params);  // mass=-M5 => diag Nd-M5, hop 1/2 (mass-norm)

  std::cout << "  building dense D_W matrix, N=" << N << std::endl;

  // Column j = D_W applied to the unit vector at (site j, spin s, colour col). Build src / read out via
  // BULK host<->device transfers (vectorizeFromLexOrdArray / unvectorizeToLexOrdArray) -- one transfer
  // per column instead of a peekSite/pokeSite per site (which would be ~V4^2 device syncs on the GPU).
  // src_h and out_h share the same lex-site index, so rows/cols are consistent (ordering is irrelevant
  // for the eigenvalue SET compare anyway).
  LatticeFermionD src(UGrid);
  LatticeFermionD out(UGrid);
  Eigen::MatrixXcd Mmat(N, N);
  std::vector<SpinColourVectorD> src_h(V4);
  std::vector<SpinColourVectorD> out_h(V4);
  for (int x = 0; x < V4; ++x) {
    src_h[x] = Zero();
  }

  for (int jsite = 0; jsite < V4; ++jsite) {
    for (int s = 0; s < Ns; ++s) {
      for (int col = 0; col < Nc; ++col) {
        int jcol = (jsite * Ns + s) * Nc + col;
        src_h[jsite]()(s)(col) = ComplexD(1.0, 0.0);
        vectorizeFromLexOrdArray(src_h, src);
        Dw.M(src, out);
        unvectorizeToLexOrdArray(out_h, out);
        for (int x = 0; x < V4; ++x) {
          for (int s2 = 0; s2 < Ns; ++s2) {
            for (int c2 = 0; c2 < Nc; ++c2) {
              int irow = (x * Ns + s2) * Nc + c2;
              ComplexD z = out_h[x]()(s2)(c2);
              Mmat(irow, jcol) = std::complex<double>(z.real(), z.imag());
            }
          }
        }
        src_h[jsite]()(s)(col) = ComplexD(0.0, 0.0);  // reset for the next column
      }
    }
  }

  // read the reference eigenvalue list (skip the "# ..." header lines)
  std::vector<std::complex<double> > ref;
  std::ifstream fin(evalfile.c_str());
  std::string line;
  while (std::getline(fin, line)) {
    if (line.empty() || line[0] == '#') {
      continue;
    }
    std::istringstream iss(line);
    double re;
    double im;
    if (iss >> re >> im) {
      ref.push_back(std::complex<double>(re, im));
    }
  }
  std::cout << "  ref eigenvalues=" << ref.size() << " (from " << evalfile << ")" << std::endl;
  if ((int)ref.size() != N) {
    std::cout << "  FAIL: ref eigenvalue count != N=" << N << std::endl;
    return false;
  }

  // ---- FAST gate: spectral moments m_k = tr(D_W^k) = sum_i lambda_i^k, k=1..K ----
  // Similarity-invariant (a K-moment match of the spectrum), and the matrix powers are threaded Eigen
  // GEMM (OMP_NUM_THREADS) -- ~seconds vs the minutes-long single-threaded complex eigensolve. K kept
  // modest so power-roundoff (lambda up to ~5.3) stays well under the gate.
  const int K = 6;
  std::vector<std::complex<double> > mk_ref(K + 1, std::complex<double>(0.0, 0.0));
  for (size_t i = 0; i < ref.size(); ++i) {
    std::complex<double> p(1.0, 0.0);
    for (int k = 1; k <= K; ++k) {
      p *= ref[i];
      mk_ref[k] += p;
    }
  }
  std::vector<std::complex<double> > mk_mine(K + 1, std::complex<double>(0.0, 0.0));
  Eigen::MatrixXcd P = Mmat;
  for (int k = 1; k <= K; ++k) {
    mk_mine[k] = P.trace();
    if (k < K) {
      P = (P * Mmat).eval();
    }
  }
  double maxrel = 0.0;
  for (int k = 1; k <= K; ++k) {
    double denom = std::abs(mk_ref[k]) + 1e-30;
    double rel = std::abs(mk_mine[k] - mk_ref[k]) / denom;
    maxrel = std::max(maxrel, rel);
    std::cout << "  moment k=" << k << "  |mine|=" << std::abs(mk_mine[k])
              << "  |ref|=" << std::abs(mk_ref[k]) << "  relerr=" << rel << std::endl;
  }
  bool ok = (maxrel < 1e-8);
  std::cout << "  spectral-moments (k=1.." << K << ") max relerr = " << maxrel << "   "
            << (ok ? "PASS" : "FAIL") << std::endl;

  // ---- optional FULL sorted-set eigenvalue match (--full-spectrum): O(N^3) complex eigensolve ----
  if (full_spectrum) {
    std::cout << "  [--full-spectrum] dense complex eigensolve, N=" << N << " (slow)..." << std::endl;
    Eigen::ComplexEigenSolver<Eigen::MatrixXcd> es(Mmat, /*computeEigenvectors=*/false);
    std::vector<std::complex<double> > mine(N);
    for (int i = 0; i < N; ++i) {
      mine[i] = es.eigenvalues()(i);
    }
    std::sort(mine.begin(), mine.end(), cmp_cplx);
    std::vector<std::complex<double> > refsorted = ref;
    std::sort(refsorted.begin(), refsorted.end(), cmp_cplx);
    double maxd = 0.0;
    for (int i = 0; i < N; ++i) {
      maxd = std::max(maxd, std::abs(mine[i] - refsorted[i]));
    }
    bool okfull = (maxd < 1e-8);
    std::cout << "  FULL sorted-set max |dlambda| = " << maxd << "   " << (okfull ? "PASS" : "FAIL")
              << std::endl;
    ok = ok && okfull;
  }
  return ok;
}

int main(int argc, char** argv) {
  Grid_init(&argc, &argv);

  const double M5 = 1.8;
  const int Ls = 8;

  // ---------- gate 0a: free D_W(p) eigenvalues ----------
  std::vector<std::array<double, 4> > mom = {
    {{0.0, 0.0, 0.0, 0.0}},
    {{0.3, 0.5, 0.7, 0.9}},
    {{1.0, 0.5, 0.25, 2.0}},
    {{1.5708, 1.0472, 0.7854, 0.6283}}
  };

  FreeMobius5DBlock K0(Ls, M5, 1.0, 1.0, 0.1);  // params irrelevant for free_dw_p
  std::cout << "==== gate 0a: free D_W(p) eigenvalues = d +- i sqrt(S) ====" << std::endl;
  double maxerr0a = 0.0;
  for (unsigned int im = 0; im < mom.size(); ++im) {
    std::array<std::complex<double>, 16> D;
    K0.free_dw_p(mom[im], D);
    Eigen::MatrixXcd M(4, 4);
    for (int a = 0; a < 4; ++a) {
      for (int bb = 0; bb < 4; ++bb) {
        M(a, bb) = D[a * 4 + bb];
      }
    }
    Eigen::ComplexEigenSolver<Eigen::MatrixXcd> es(M);

    double dsc = 4.0 - M5;
    double S = 0.0;
    for (int mu = 0; mu < 4; ++mu) {
      dsc -= std::cos(mom[im][mu]);
      S += std::sin(mom[im][mu]) * std::sin(mom[im][mu]);
    }
    std::complex<double> lp(dsc, std::sqrt(S));
    std::complex<double> lm(dsc, -std::sqrt(S));

    double emax = 0.0;
    for (int i = 0; i < 4; ++i) {
      std::complex<double> lam = es.eigenvalues()(i);
      double e = std::min(std::abs(lam - lp), std::abs(lam - lm));
      emax = std::max(emax, e);
    }
    maxerr0a = std::max(maxerr0a, emax);
    std::cout << "  p=(" << mom[im][0] << "," << mom[im][1] << "," << mom[im][2] << "," << mom[im][3]
              << ")  d=" << dsc << "  S=" << S << "  expect " << dsc << " +- i" << std::sqrt(S)
              << "  max|dev|=" << emax << std::endl;
  }
  std::cout << "  gate 0a max eig error = " << maxerr0a << "   "
            << (maxerr0a < 1e-10 ? "PASS" : "FAIL") << std::endl;

  // ---------- gate 0b: free Mobius block extremes vs table ----------
  struct Case {
    double b;
    double c;
    double m;
    const char* name;
  };
  std::vector<Case> cases = {
    {1.0, 1.0, 0.1, "control b=c=1  m=0.100"},
    {1.0, 1.0, 0.02, "control b=c=1  m=0.020"},
    {1.5, 0.5, 0.1, "Shamir  b=1.5,c=0.5  m=0.100"},
    {1.5, 0.5, 0.02, "Shamir  b=1.5,c=0.5  m=0.020"}
  };
  std::vector<std::array<double, 4> > mom3 = {mom[1], mom[2], mom[3]};

  // expected [case][mom][{min,max}] |lambda| from grid_validation_evals_claude.md
  double expext[4][3][2] = {
    {{1.687531, 3.033442}, {1.913130, 2.715880}, {1.917360, 3.205270}},
    {{1.674845, 3.030728}, {1.910613, 2.715812}, {1.913318, 3.205445}},
    {{1.552844, 3.038772}, {2.584426, 2.733246}, {2.720519, 3.223767}},
    {{1.546686, 3.038398}, {2.586628, 2.732889}, {2.718903, 3.223748}}
  };

  std::cout << "==== gate 0b: free Mobius block (4Ls)x(4Ls) min/max |lambda| vs table ===="
            << std::endl;
  double maxrel0b = 0.0;
  for (unsigned int ci = 0; ci < cases.size(); ++ci) {
    FreeMobius5DBlock K(Ls, M5, cases[ci].b, cases[ci].c, cases[ci].m);
    std::cout << "  -- " << cases[ci].name << std::endl;
    for (int mi = 0; mi < 3; ++mi) {
      Eigen::MatrixXcd M = K.build_block(mom3[mi]);
      Eigen::ComplexEigenSolver<Eigen::MatrixXcd> es(M);
      std::vector<double> absl;
      for (int i = 0; i < M.rows(); ++i) {
        absl.push_back(std::abs(es.eigenvalues()(i)));
      }
      std::sort(absl.begin(), absl.end());
      double mn = absl.front();
      double mx = absl.back();
      double emn = std::abs(mn - expext[ci][mi][0]) / expext[ci][mi][0];
      double emx = std::abs(mx - expext[ci][mi][1]) / expext[ci][mi][1];
      maxrel0b = std::max(maxrel0b, std::max(emn, emx));
      std::cout << "     mom" << mi << "  min|l|=" << mn << " (exp " << expext[ci][mi][0] << ")"
                << "  max|l|=" << mx << " (exp " << expext[ci][mi][1] << ")"
                << "  relerr=" << std::max(emn, emx) << std::endl;
    }
  }
  std::cout << "  gate 0b max rel error = " << maxrel0b << "   "
            << (maxrel0b < 1e-4 ? "PASS" : "FAIL") << std::endl;

  // ---------- gate 1: cold gate on unit gauge, BOTH directions ----------
  // F = D_DW^free(m)^-1 must invert Grid's actual MobiusFermionD operator on unit gauge. Both
  // directions guard against a twist/boundary sign error passing one way and failing the other.
  std::cout << "==== gate 1: cold gate  ||F D v - v|| and ||D F v - v|| (unit gauge) ====" << std::endl;
  Coordinate latt = GridDefaultLatt();
  Coordinate simd = GridDefaultSimd(Nd, vComplexD::Nsimd());
  Coordinate mpi = GridDefaultMpi();
  GridCartesian* UGrid = SpaceTimeGrid::makeFourDimGrid(latt, simd, mpi);
  GridRedBlackCartesian* UrbGrid = SpaceTimeGrid::makeFourDimRedBlackGrid(UGrid);
  GridCartesian* FGrid = SpaceTimeGrid::makeFiveDimGrid(Ls, UGrid);
  GridRedBlackCartesian* FrbGrid = SpaceTimeGrid::makeFiveDimRedBlackGrid(Ls, UGrid);

  LatticeGaugeFieldD Umu(UGrid);
  SU<Nc>::ColdConfiguration(Umu);  // unit gauge (identity links)

  const double bb = 1.5;   // headline Shamir point
  const double cc = 0.5;
  const double mm = 0.1;
  std::vector<Complex> boundary = {1, 1, 1, -1};  // anti-periodic time
  MobiusFermionD::ImplParams Params(boundary);
  MobiusFermionD Dfree(Umu, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);

  FreeMobius5DInverse<WilsonImplD> F(FGrid, Ls, M5, bb, cc, mm, boundary);

  GridParallelRNG RNG5(FGrid);
  RNG5.SeedFixedIntegers(std::vector<int>({1, 2, 3, 4}));
  LatticeFermionD v(FGrid);
  LatticeFermionD Dv(FGrid);
  LatticeFermionD FDv(FGrid);
  LatticeFermionD Fv(FGrid);
  LatticeFermionD DFv(FGrid);
  gaussian(RNG5, v);

  Dfree.M(v, Dv);
  F(Dv, FDv);
  double e1 = std::sqrt(norm2(FDv - v) / norm2(v));

  F(v, Fv);
  Dfree.M(Fv, DFv);
  double e2 = std::sqrt(norm2(DFv - v) / norm2(v));

#ifdef FREEMOBIUS5D_USE_FP32
  double gtol1 = 5.0e-5;  // single-precision F apply (DEFAULT): cold gate is ~single eps, still exact-in-single
#else
  double gtol1 = 1.0e-10;
#endif
  bool gate1 = (e1 < gtol1) && (e2 < gtol1);
  std::cout << "  ||F D v - v||/||v|| = " << e1 << "   ||D F v - v||/||v|| = " << e2 << "   "
            << (gate1 ? "PASS" : "FAIL") << std::endl;

  bool have_cfg = GridCmdOptionExists(argv, argv + argc, "--config");
  bool gate2 = true;

  // ADDITIVE op selection: --ops <comma-list of cgne,m0,m1> chooses which headline solves to run.
  // Default (no --ops) = all three. Nobu: add, don't restrict -- naming an op turns it ON, and an op
  // NOT run this pass is taken from the prior freeprec_<cfg>_claude.log for any cross-op ratio.
  bool run_cgne = true;
  bool run_m0 = true;
  bool run_m1 = true;
  if (GridCmdOptionExists(argv, argv + argc, "--ops")) {
    std::string ops = GridCmdOptionPayload(argv, argv + argc, "--ops");
    run_cgne = (ops.find("cgne") != std::string::npos);
    run_m0 = (ops.find("m0") != std::string::npos);
    run_m1 = (ops.find("m1") != std::string::npos);
    g_run_bcg = (ops.find("bcg") != std::string::npos);  // BiCGSTAB(M0) A/B vs FGMRES
  }
  // outer-solver knob: --restart N sets the FGMRES restart length (default 256 = no-restart). Lower N
  // caps the O(iters^2) orthogonalization at the cost of possibly more iterations.
  if (GridCmdOptionExists(argv, argv + argc, "--restart")) {
    g_fgmres_restart = std::stoi(GridCmdOptionPayload(argv, argv + argc, "--restart"));
  }
  // --restart-sweep a,b,c : FGMRES solves at each restart length back-to-back (same frame, pins optimum).
  if (GridCmdOptionExists(argv, argv + argc, "--restart-sweep")) {
    GridCmdOptionIntVector(GridCmdOptionPayload(argv, argv + argc, "--restart-sweep"), g_restart_sweep);
  }

  // FLOW-TIME SCAN (Direction 1b Stage 1): --flow_nsteps <comma list> switches the --config headline to a
  // tau-scan (run_flowscan: CGNE once, then flow -> Landau -> M0/M1 per tau). --t0 maps tau -> s/t0 in
  // the printout; --solve_tol overrides the solver tolerance (Nobu: 1e-6 for the scan).
  std::vector<int> flow_nsteps;
  if (GridCmdOptionExists(argv, argv + argc, "--flow_nsteps")) {
    std::string a = GridCmdOptionPayload(argv, argv + argc, "--flow_nsteps");
    std::stringstream ss(a);
    std::string tok;
    while (std::getline(ss, tok, ',')) {
      if (!tok.empty()) {
        flow_nsteps.push_back(std::stoi(tok));
      }
    }
  }
  double scan_t0 = 1.0;
  if (GridCmdOptionExists(argv, argv + argc, "--t0")) {
    std::string a = GridCmdOptionPayload(argv, argv + argc, "--t0");
    GridCmdOptionFloat(a, scan_t0);
  }
  double scan_tol = 1.0e-8;
  if (GridCmdOptionExists(argv, argv + argc, "--solve_tol")) {
    std::string a = GridCmdOptionPayload(argv, argv + argc, "--solve_tol");
    GridCmdOptionFloat(a, scan_tol);
  }

  // gate 2 (pure-gauge) + the Hot-config shakeout are config-INDEPENDENT validations. Skip BOTH for a
  // real --config run: gate 2 is already validated at 4^4, and its pure-gauge fix uses alpha=0.1 (the
  // uncorrected 16x-too-large step) which could diverge at 8^4 and spuriously fail the run. Gate 1
  // above already re-validates the (now bulk-transfer) F apply at the run's volume.
  if (!have_cfg) {
    // ---------- gate 2: pure-gauge gate ----------
    // U^g = g0 . 1 . g0^dag (pure gauge). Landau-fix a COPY -> Omega = xform, U^L ~ 1. M0 = Omega^dag F
    // Omega must invert D_DW built on the ORIGINAL U^g (fix only supplies the frame; solve the original).
    std::cout << "==== gate 2: pure-gauge gate  ||M0 D[U^g] v - v|| ====" << std::endl;
    GridParallelRNG RNG4(UGrid);
    RNG4.SeedFixedIntegers(std::vector<int>({5, 6, 7, 8}));

    LatticeGaugeFieldD Ug(UGrid);
    SU<Nc>::ColdConfiguration(Ug);
    LatticeColourMatrixD g0(UGrid);
    SU<Nc>::RandomGaugeTransform<PeriodicGimplD>(RNG4, Ug, g0);  // Ug = g0 . 1 . g0^dag

    LatticeGaugeFieldD Ufix = Ug;  // fix a COPY; D_DW uses the original Ug
    LatticeColourMatrixD xform(UGrid);
    Real alpha = 0.1;
    int gfmaxit = 5000;
    Real gftol = 1.0e-12;
    FourierAcceleratedGaugeFixer<PeriodicGimplD>::SteepestDescentGaugeFix(
        Ufix, xform, alpha, gfmaxit, gftol, gftol, /*Fourier=*/true, /*orthog=*/-1,
        /*err_on_no_converge=*/false);

    Real plaq_fix = WilsonLoops<PeriodicGimplD>::avgPlaquette(Ufix);
    Real link_fix = WilsonLoops<PeriodicGimplD>::linkTrace(Ufix);
    Real landau_func = 1.0 - link_fix;  // Landau functional; -> 0 iff U^L -> 1 (frame quality, R1)
    Real Qtop = WilsonLoops<PeriodicGimplD>::TopologicalCharge(Ug);
    std::cout << "  fixed-config plaquette = " << plaq_fix << "  (pure gauge -> ~1)"
              << "   Landau functional 1-linkTrace = " << landau_func << "  (-> 0 iff U^L -> 1)"
              << "   topo charge Q = " << Qtop << std::endl;

    MobiusFermionD Dg(Ug, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
    FreeMobius5DInverse<WilsonImplD> Ffree(FGrid, Ls, M5, bb, cc, mm, boundary);
    FreeLimitPreconditioner<WilsonImplD> M0(Ffree, xform, FGrid);

    LatticeFermionD v2(FGrid);
    LatticeFermionD Dgv(FGrid);
    LatticeFermionD M0Dgv(FGrid);
    gaussian(RNG5, v2);
    Dg.M(v2, Dgv);
    M0(Dgv, M0Dgv);
    double e3 = std::sqrt(norm2(M0Dgv - v2) / norm2(v2));
    gate2 = (e3 < 1e-6);
    std::cout << "  ||M0 D[U^g] v - v||/||v|| = " << e3 << "   " << (gate2 ? "PASS" : "FAIL") << std::endl;

    // ---------- Hot-config shakeout (plumbing/counting; not the physics win) ----------
    LatticeGaugeFieldD Uh(UGrid);
    SU<Nc>::HotConfiguration(RNG4, Uh);
    run_headline("Hot config -- shakeout", Uh, UGrid, UrbGrid, FGrid, FrbGrid,
                 Ls, M5, bb, cc, mm, boundary, 0.02, 100, RNG5, run_cgne, run_m0, run_m1);
  }

  // ---------- chunk 3b: NERSC config cross-check + headline (only if --config <nersc-file> given) ----------
  bool gate3b = true;
  if (have_cfg) {
    std::string cfgfile = GridCmdOptionPayload(argv, argv + argc, "--config");
    std::string evalfile = "/mnt/baracuda_14/dwms/dwf4_qcd_claude/cfg_su3_4444_b6.0_dw_evals_claude.dat";
    if (GridCmdOptionExists(argv, argv + argc, "--evals")) {
      evalfile = GridCmdOptionPayload(argv, argv + argc, "--evals");
    }
    LatticeGaugeFieldD Ureal(UGrid);
    FieldMetaData rheader;
    NerscIO::readConfiguration(Ureal, rheader, cfgfile);
    Real plaqr = WilsonLoops<PeriodicGimplD>::avgPlaquette(Ureal);
    std::cout << "  loaded " << cfgfile << std::endl;
    std::cout << "  plaquette: computed=" << plaqr << "  header=" << rheader.plaquette
              << "  |diff|=" << std::fabs(plaqr - rheader.plaquette) << std::endl;
    bool full_spectrum = GridCmdOptionExists(argv, argv + argc, "--full-spectrum");
    gate3b = nersc_crosscheck(Ureal, evalfile, UGrid, UrbGrid, M5, boundary, full_spectrum);
    if (!flow_nsteps.empty()) {
      run_flowscan("NERSC SU(3) -- FLOW-TIME SCAN", Ureal, UGrid, UrbGrid, FGrid, FrbGrid,
                   Ls, M5, bb, cc, mm, boundary, 0.02, flow_nsteps, scan_t0, RNG5,
                   run_cgne, run_m0, run_m1, scan_tol);
    } else {
      run_headline("NERSC SU(3) beta6 -- HEADLINE", Ureal, UGrid, UrbGrid, FGrid, FrbGrid,
                   Ls, M5, bb, cc, mm, boundary, 0.02, 100, RNG5, run_cgne, run_m0, run_m1);
    }
  }

  bool pass = (maxerr0a < 1e-10) && (maxrel0b < 1e-4) && gate1 && gate2 && gate3b;
  std::cout << "==== CHUNK 0+1+2" << (have_cfg ? "+3b" : "") << " " << (pass ? "PASS" : "FAIL")
            << (have_cfg ? "" : " (pass --config for the 3b headline + cross-check)") << " ====" << std::endl;

  Grid_finalize();
  return pass ? 0 : 1;
}
