// Chunk 0 of the free-limit Mobius domain-wall preconditioner (Grid port).
// See dwf4_qcd_claude/grid_dwf_prec_impl_plan_claude.md.
//
// Gate 0 = free-operator convention gate, config-INDEPENDENT, validates the momentum-space SPECTRAL
// BLOCK ("the eigenvalues") that replaces Grid's Shamir-only FreePropagator momentum kernel:
//   0a: free D_W(p) eigenvalues = d +- i sqrt(S)   [d = (Nd-M5) - sum cos p, S = sum sin^2 p]
//   0b: free Mobius block (4 Ls)x(4 Ls) min/max |lambda| vs grid_validation_evals_claude.md
// Reference table generated by dwf4_free_evals_claude.py; must match to ~1e-4 (table printed to 7 sig
// figs; the underlying construction agrees to ~1e-12).
//
// NB (user 2026-08-31): Shamir -> Mobius changes eigenvalues AND eigenvectors, so gate 0b is
// NECESSARY-BUT-NOT-SUFFICIENT; the full inverse (values + vectors) is checked by the chunk-1 cold gate.

#include <Grid/Grid.h>
#include <Grid/qcd/utils/FreeMobius5D_claude.h>

#include <array>
#include <vector>
#include <complex>
#include <algorithm>
#include <cmath>

using namespace Grid;

int main(int argc, char** argv) {
  Grid_init(&argc, &argv);

  const double M5 = 1.8;
  const int Ls = 8;

  // ---------- gate 0a: free D_W(p) eigenvalues ----------
  std::vector<std::array<double, 4> > mom = {
    {{0.0, 0.0, 0.0, 0.0}},
    {{0.3, 0.5, 0.7, 0.9}},
    {{1.0, 0.5, 0.25, 2.0}},
    {{1.5708, 1.0472, 0.7854, 0.6283}}
  };

  FreeMobius5DBlock K0(Ls, M5, 1.0, 1.0, 0.1);  // params irrelevant for free_dw_p
  std::cout << "==== gate 0a: free D_W(p) eigenvalues = d +- i sqrt(S) ====" << std::endl;
  double maxerr0a = 0.0;
  for (unsigned int im = 0; im < mom.size(); ++im) {
    std::array<std::complex<double>, 16> D;
    K0.free_dw_p(mom[im], D);
    Eigen::MatrixXcd M(4, 4);
    for (int a = 0; a < 4; ++a) {
      for (int bb = 0; bb < 4; ++bb) {
        M(a, bb) = D[a * 4 + bb];
      }
    }
    Eigen::ComplexEigenSolver<Eigen::MatrixXcd> es(M);

    double dsc = 4.0 - M5;
    double S = 0.0;
    for (int mu = 0; mu < 4; ++mu) {
      dsc -= std::cos(mom[im][mu]);
      S += std::sin(mom[im][mu]) * std::sin(mom[im][mu]);
    }
    std::complex<double> lp(dsc, std::sqrt(S));
    std::complex<double> lm(dsc, -std::sqrt(S));

    double emax = 0.0;
    for (int i = 0; i < 4; ++i) {
      std::complex<double> lam = es.eigenvalues()(i);
      double e = std::min(std::abs(lam - lp), std::abs(lam - lm));
      emax = std::max(emax, e);
    }
    maxerr0a = std::max(maxerr0a, emax);
    std::cout << "  p=(" << mom[im][0] << "," << mom[im][1] << "," << mom[im][2] << "," << mom[im][3]
              << ")  d=" << dsc << "  S=" << S << "  expect " << dsc << " +- i" << std::sqrt(S)
              << "  max|dev|=" << emax << std::endl;
  }
  std::cout << "  gate 0a max eig error = " << maxerr0a << "   "
            << (maxerr0a < 1e-10 ? "PASS" : "FAIL") << std::endl;

  // ---------- gate 0b: free Mobius block extremes vs table ----------
  struct Case {
    double b;
    double c;
    double m;
    const char* name;
  };
  std::vector<Case> cases = {
    {1.0, 1.0, 0.1, "control b=c=1  m=0.100"},
    {1.0, 1.0, 0.02, "control b=c=1  m=0.020"},
    {1.5, 0.5, 0.1, "Shamir  b=1.5,c=0.5  m=0.100"},
    {1.5, 0.5, 0.02, "Shamir  b=1.5,c=0.5  m=0.020"}
  };
  std::vector<std::array<double, 4> > mom3 = {mom[1], mom[2], mom[3]};

  // expected [case][mom][{min,max}] |lambda| from grid_validation_evals_claude.md
  double expext[4][3][2] = {
    {{1.687531, 3.033442}, {1.913130, 2.715880}, {1.917360, 3.205270}},
    {{1.674845, 3.030728}, {1.910613, 2.715812}, {1.913318, 3.205445}},
    {{1.552844, 3.038772}, {2.584426, 2.733246}, {2.720519, 3.223767}},
    {{1.546686, 3.038398}, {2.586628, 2.732889}, {2.718903, 3.223748}}
  };

  std::cout << "==== gate 0b: free Mobius block (4Ls)x(4Ls) min/max |lambda| vs table ===="
            << std::endl;
  double maxrel0b = 0.0;
  for (unsigned int ci = 0; ci < cases.size(); ++ci) {
    FreeMobius5DBlock K(Ls, M5, cases[ci].b, cases[ci].c, cases[ci].m);
    std::cout << "  -- " << cases[ci].name << std::endl;
    for (int mi = 0; mi < 3; ++mi) {
      Eigen::MatrixXcd M = K.build_block(mom3[mi]);
      Eigen::ComplexEigenSolver<Eigen::MatrixXcd> es(M);
      std::vector<double> absl;
      for (int i = 0; i < M.rows(); ++i) {
        absl.push_back(std::abs(es.eigenvalues()(i)));
      }
      std::sort(absl.begin(), absl.end());
      double mn = absl.front();
      double mx = absl.back();
      double emn = std::abs(mn - expext[ci][mi][0]) / expext[ci][mi][0];
      double emx = std::abs(mx - expext[ci][mi][1]) / expext[ci][mi][1];
      maxrel0b = std::max(maxrel0b, std::max(emn, emx));
      std::cout << "     mom" << mi << "  min|l|=" << mn << " (exp " << expext[ci][mi][0] << ")"
                << "  max|l|=" << mx << " (exp " << expext[ci][mi][1] << ")"
                << "  relerr=" << std::max(emn, emx) << std::endl;
    }
  }
  std::cout << "  gate 0b max rel error = " << maxrel0b << "   "
            << (maxrel0b < 1e-4 ? "PASS" : "FAIL") << std::endl;

  // ---------- gate 1: cold gate on unit gauge, BOTH directions ----------
  // F = D_DW^free(m)^-1 must invert Grid's actual MobiusFermionD operator on unit gauge. Both
  // directions guard against a twist/boundary sign error passing one way and failing the other.
  std::cout << "==== gate 1: cold gate  ||F D v - v|| and ||D F v - v|| (unit gauge) ====" << std::endl;
  Coordinate latt = GridDefaultLatt();
  Coordinate simd = GridDefaultSimd(Nd, vComplexD::Nsimd());
  Coordinate mpi = GridDefaultMpi();
  GridCartesian* UGrid = SpaceTimeGrid::makeFourDimGrid(latt, simd, mpi);
  GridRedBlackCartesian* UrbGrid = SpaceTimeGrid::makeFourDimRedBlackGrid(UGrid);
  GridCartesian* FGrid = SpaceTimeGrid::makeFiveDimGrid(Ls, UGrid);
  GridRedBlackCartesian* FrbGrid = SpaceTimeGrid::makeFiveDimRedBlackGrid(Ls, UGrid);

  LatticeGaugeFieldD Umu(UGrid);
  SU<Nc>::ColdConfiguration(Umu);  // unit gauge (identity links)

  const double bb = 1.5;   // headline Shamir point
  const double cc = 0.5;
  const double mm = 0.1;
  std::vector<Complex> boundary = {1, 1, 1, -1};  // anti-periodic time
  MobiusFermionD::ImplParams Params(boundary);
  MobiusFermionD Dfree(Umu, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);

  FreeMobius5DInverse<WilsonImplD> F(FGrid, Ls, M5, bb, cc, mm, boundary);

  GridParallelRNG RNG5(FGrid);
  RNG5.SeedFixedIntegers(std::vector<int>({1, 2, 3, 4}));
  LatticeFermionD v(FGrid);
  LatticeFermionD Dv(FGrid);
  LatticeFermionD FDv(FGrid);
  LatticeFermionD Fv(FGrid);
  LatticeFermionD DFv(FGrid);
  gaussian(RNG5, v);

  Dfree.M(v, Dv);
  F(Dv, FDv);
  double e1 = std::sqrt(norm2(FDv - v) / norm2(v));

  F(v, Fv);
  Dfree.M(Fv, DFv);
  double e2 = std::sqrt(norm2(DFv - v) / norm2(v));

  bool gate1 = (e1 < 1e-10) && (e2 < 1e-10);
  std::cout << "  ||F D v - v||/||v|| = " << e1 << "   ||D F v - v||/||v|| = " << e2 << "   "
            << (gate1 ? "PASS" : "FAIL") << std::endl;

  // ---------- gate 2: pure-gauge gate ----------
  // U^g = g0 . 1 . g0^dag (pure gauge). Landau-fix a COPY -> Omega = xform, U^L ~ 1. M0 = Omega^dag F
  // Omega must invert D_DW built on the ORIGINAL U^g (flow/fix only supply the frame; solve the original).
  std::cout << "==== gate 2: pure-gauge gate  ||M0 D[U^g] v - v|| ====" << std::endl;
  GridParallelRNG RNG4(UGrid);
  RNG4.SeedFixedIntegers(std::vector<int>({5, 6, 7, 8}));

  LatticeGaugeFieldD Ug(UGrid);
  SU<Nc>::ColdConfiguration(Ug);
  LatticeColourMatrixD g0(UGrid);
  SU<Nc>::RandomGaugeTransform<PeriodicGimplD>(RNG4, Ug, g0);  // Ug = g0 . 1 . g0^dag

  LatticeGaugeFieldD Ufix = Ug;  // fix a COPY; D_DW uses the original Ug
  LatticeColourMatrixD xform(UGrid);
  Real alpha = 0.1;
  int gfmaxit = 5000;
  Real gftol = 1.0e-12;
  FourierAcceleratedGaugeFixer<PeriodicGimplD>::SteepestDescentGaugeFix(
      Ufix, xform, alpha, gfmaxit, gftol, gftol, /*Fourier=*/true, /*orthog=*/-1,
      /*err_on_no_converge=*/false);

  Real plaq_fix = WilsonLoops<PeriodicGimplD>::avgPlaquette(Ufix);
  Real link_fix = WilsonLoops<PeriodicGimplD>::linkTrace(Ufix);
  Real landau_func = 1.0 - link_fix;  // Landau functional; -> 0 iff U^L -> 1 (frame quality, R1)
  Real Qtop = WilsonLoops<PeriodicGimplD>::TopologicalCharge(Ug);
  std::cout << "  fixed-config plaquette = " << plaq_fix << "  (pure gauge -> ~1)"
            << "   Landau functional 1-linkTrace = " << landau_func << "  (-> 0 iff U^L -> 1)"
            << "   topo charge Q = " << Qtop << std::endl;

  MobiusFermionD Dg(Ug, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
  FreeMobius5DInverse<WilsonImplD> Ffree(FGrid, Ls, M5, bb, cc, mm, boundary);
  FreeLimitPreconditioner<WilsonImplD> M0(Ffree, xform, FGrid);

  LatticeFermionD v2(FGrid);
  LatticeFermionD Dgv(FGrid);
  LatticeFermionD M0Dgv(FGrid);
  gaussian(RNG5, v2);
  Dg.M(v2, Dgv);
  M0(Dgv, M0Dgv);
  double e3 = std::sqrt(norm2(M0Dgv - v2) / norm2(v2));
  bool gate2 = (e3 < 1e-6);
  std::cout << "  ||M0 D[U^g] v - v||/||v|| = " << e3 << "   " << (gate2 ? "PASS" : "FAIL") << std::endl;

  // ---------- chunk 3 harness (shakeout on a Hot config; headline needs a thermalized config) ----------
  // Frame = WilsonFlow(eps=0.02 x 100, tau=2.0) then Fourier Landau (dwf4 params). Solve the ORIGINAL
  // config. Metric (dwf4): D_W applies = CGNE 2*Ls*iters (normal op = 2 M/iter), FGMRES Ls*iters
  // (1 M/iter; M0 costs 0 D_W). NB a raw Hot config is not thermalized -- this validates the plumbing +
  // counting, not the physics win; the 5-16x headline needs the NERSC SU(3) beta6 config (chunk 3b).
  std::cout << "==== chunk 3 harness: FGMRES(M0) vs CGNE D_W-count (Hot config, shakeout) ====" << std::endl;
  LatticeGaugeFieldD Uh(UGrid);
  SU<Nc>::HotConfiguration(RNG4, Uh);
  Real plaq_hot = WilsonLoops<PeriodicGimplD>::avgPlaquette(Uh);

  LatticeGaugeFieldD Uflowed(UGrid);
  WilsonFlow<PeriodicGimplD> wf(0.02, 100);  // eps=0.02, 100 steps -> tau=2.0
  wf.smear(Uflowed, Uh);
  Real plaq_flowed = WilsonLoops<PeriodicGimplD>::avgPlaquette(Uflowed);
  LatticeColourMatrixD xform3(UGrid);
  FourierAcceleratedGaugeFixer<PeriodicGimplD>::SteepestDescentGaugeFix(
      Uflowed, xform3, alpha, gfmaxit, gftol, gftol, /*Fourier=*/true, /*orthog=*/-1,
      /*err_on_no_converge=*/false);
  Real landau3 = 1.0 - WilsonLoops<PeriodicGimplD>::linkTrace(Uflowed);
  Real Q3 = WilsonLoops<PeriodicGimplD>::TopologicalCharge(Uh);
  std::cout << "  hot plaq=" << plaq_hot << "  flowed plaq=" << plaq_flowed
            << "  flowed-fixed Landau functional=" << landau3 << "  Q(orig)=" << Q3 << std::endl;

  MobiusFermionD Dh(Uh, *FGrid, *FrbGrid, *UGrid, *UrbGrid, mm, M5, bb, cc, Params);
  FreeMobius5DInverse<WilsonImplD> Ffree3(FGrid, Ls, M5, bb, cc, mm, boundary);
  FreeLimitPreconditioner<WilsonImplD> M0h(Ffree3, xform3, FGrid);

  LatticeFermionD bsrc(FGrid);
  gaussian(RNG5, bsrc);
  RealD solve_tol = 1.0e-8;
  int solve_maxit = 4000;
  // "no-restart" must be a RestartLength ABOVE the expected iteration count, NOT literally maxit:
  // FlexibleGMRES pre-allocates RestartLength+1 Krylov fermion fields + an (RestartLength)^2 H matrix,
  // so restart=maxit=20000 OOMs the GPU. 256 >> the ~71-iter headline => effectively no restart.
  int fgmres_restart = 256;

  // CGNE baseline: CG on MdagM with src = Mdag b
  MdagMLinearOperator<MobiusFermionD, LatticeFermionD> HermOp(Dh);
  LatticeFermionD bn(FGrid);
  Dh.Mdag(bsrc, bn);
  LatticeFermionD xcg(FGrid);
  xcg = Zero();
  ConjugateGradient<LatticeFermionD> CG(solve_tol, solve_maxit);
  CG(HermOp, bn, xcg);
  int cg_iters = CG.IterationsToComplete;
  long dW_cgne = (long)2 * Ls * cg_iters;

  // FGMRES right-preconditioned by M0, no restart
  NonHermitianLinearOperator<MobiusFermionD, LatticeFermionD> LinOp(Dh);
  M0h.n_apply = 0;
  FlexibleGeneralisedMinimalResidual<LatticeFermionD> FGMRES(solve_tol, solve_maxit, M0h,
                                                            /*restart=*/fgmres_restart,
                                                            /*err_on_no_conv=*/false);
  LatticeFermionD xg(FGrid);
  xg = Zero();
  FGMRES(LinOp, bsrc, xg);
  int fg_iters = FGMRES.IterationCount;
  long dW_fgmres = (long)Ls * fg_iters;

  std::cout << "  CGNE:       iters=" << cg_iters << "  D_W applies=" << dW_cgne << std::endl;
  std::cout << "  FGMRES(M0): iters=" << fg_iters << "  M0 applies=" << M0h.n_apply
            << "  D_W applies=" << dW_fgmres << std::endl;
  double speedup = (dW_fgmres > 0) ? (double)dW_cgne / (double)dW_fgmres : 0.0;
  std::cout << "  D_W-apply speedup (CGNE / FGMRES) = " << speedup << "x  (Hot config -- plumbing check)"
            << std::endl;

  bool pass = (maxerr0a < 1e-10) && (maxrel0b < 1e-4) && gate1 && gate2;
  std::cout << "==== CHUNK 0+1+2 " << (pass ? "PASS" : "FAIL")
            << " (chunk-3 harness ran; headline pending thermalized config) ====" << std::endl;

  Grid_finalize();
  return pass ? 0 : 1;
}
